apiVersion: v1
kind: Service
metadata:
  name: ml-inference
spec:
  selector:
    app: ml-inference
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort  # Use NodePort for local clusters like Minikube